---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-test
  labels:
    app: mysql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-test
  template:
    metadata:
      labels:
        app : mysql-test
    spec:
      containers:
        - name: mysql-test
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/
              name: db-data
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db-pass
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data

      initContainers:
        - name: busybox
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          args: ["rm","-rf","/var/lib/mysql/*"]

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: dockerhub-cred

